module.exports = {
  SEND_BOARD: 'sendBoard',
  SEND_PLAYERS: 'sendPlayers',
  PLAYER_CONNECTED: 'playerConnected',
  ADD_TILES: 'addTiles',
  NOTIFY_START: 'notifyStart',
  YOUR_TURN: 'yourTurn',
  NEXT_PLAYER: 'nextPlayer',
  PLACE: 'place',
  AWAITING_ACCEPTANCE: 'awaitingAcceptance',
  AWAITING_OTHERS_ACCEPTANCE: 'awaitingOthersAcceptance',
  WORD_ACCEPT: 'wordAccept',
  WORD_CHECK: 'wordCheck',
  UPDATE_SCORE: 'updateScore',
  SWAP: 'swap',
  SWAP_CANCELLED: 'swapCancelled',
  SWAP_ACCEPTED: 'swapAccepted',
  HOLD: 'hold',
};
